backendStore:
  databaseMigration: true
  postgres:
    enabled: true
    host: postgres-postgresql.postgres.svc.cluster.local
    port: 5432
    database: postgres
    user: postgres
    password: postgres

artifactRoot:
  s3:
    enabled: true
    bucket: mlflow
    awsAccessKeyId: minio123
    awsSecretAccessKey: minio123

extraEnvVars:
  MLFLOW_S3_ENDPOINT_URL: http://minio.minio-storage:80